"""empty message

Revision ID: 90795f61286a
Revises: 8bf0ed428498
Create Date: 2020-11-09 14:46:34.114809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90795f61286a'
down_revision = '8bf0ed428498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_project')
    # ### end Alembic commands ###
